/**
 * Payment types for x402 protocol and BitGo wallet integration
 */

import type { HexString } from './zk.js';

/** x402 payment details */
export interface PaymentDetails {
  /** Payment address on Base */
  payTo: HexString;
  /** Amount in USDC (6 decimals) */
  amount: string;
  /** Chain ID (Base = 8453, Base Sepolia = 84532) */
  chainId: number;
  /** Token address (USDC on Base) */
  tokenAddress: HexString;
  /** Payment memo/reference */
  memo: string;
}

/** x402 payment proof */
export interface PaymentProof {
  /** Transaction hash on Base */
  txHash: HexString;
  /** Block number */
  blockNumber: number;
  /** Amount paid */
  amount: string;
  /** Payer address */
  payer: HexString;
}

/** Payment split configuration */
export interface PaymentSplit {
  /** Relay 1 share (basis points, e.g., 3000 = 30%) */
  relay1Share: number;
  /** Relay 2 share */
  relay2Share: number;
  /** Relay 3 share */
  relay3Share: number;
  /** Protocol fee share */
  protocolShare: number;
}

// ─── BitGo wallet payment types ─────────────────────────────────────────────

/** A one-time receive address generated by BitGo for stealth payments */
export interface StealthAddress {
  /** The generated address */
  address: string;
  /** BitGo internal address ID */
  addressId: string;
  /** Which wallet this address belongs to */
  walletId: string;
  /** Human-readable label (for auditing, never on-chain) */
  label?: string;
  /** When this address was generated */
  createdAt: number;
}

/** Receipt from a BitGo stealth-address disbursement */
export interface BitGoDisbursementReceipt {
  /** BitGo transaction ID */
  txid: string;
  /** Per-recipient breakdown */
  splits: Array<{
    /** Relay ENS name or 'protocol' */
    recipient: string;
    /** Fresh address used for this disbursement */
    address: string;
    /** Amount in base units */
    amount: string;
    /** Whether a fresh address was generated (true) or a fixed address was used */
    isStealth: boolean;
  }>;
  /** Total amount disbursed */
  totalAmount: string;
  /** When the disbursement was initiated */
  timestamp: number;
}

/** BitGo wallet status for health checks */
export interface BitGoWalletStatus {
  /** Whether BitGo integration is enabled */
  enabled: boolean;
  /** Wallet balance in base units */
  balance?: string;
  /** Confirmed balance */
  confirmedBalance?: string;
  /** Coin identifier */
  coin?: string;
  /** BitGo environment */
  env?: string;
}
